dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
branches: 
only:
- master
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis.py local_settings.py
- python ./manage.py test --keepdb
notifications:
  email: false
deploy:
  provider: heroku
  app: herokuegctest
  strategy: git
  api_key:
    secure: lWFmhaC8Cwk7mdnky/zZch070wzcHfIfVthlAga7lNrIQlYBRmu9eSYioKXJ6DhsaEWSi0swu6Fl/PqtT87QcyXuNIuA2NRlHXuWPbaOlf+/j+N905DpfCWa7MdxgbAJH+6oSo4FH8GQX72Fv23U96XhCE01egoTQ2dxQKzmhPhxMW3IHmkNKphZijOJWf/v5MDnnYm9MXCTYIJOgeniZSFIzuZZocX1wAvaCr06mQJ/H/UGoVca4m+smcLLExbP1bzz6rmyVdwm6e29VCIXbEuodVyNBXxQ87x3DNOcwWGzDG9sVDM5uPO/kw0ZOw4+HzEOM2G1o2FXf1f7mM16XMLQz1jcTWPzmuvIqAnkRuyOr1lawIrPLzfoSCDRfJ5IyG7mebMiqNERsIs4XZBPRmC0FxZlIeMkckSkBXzOMIOAMEaXPAfPxQO1D8cHHxP20gqtRT96FIRdRlNqWVh64yTGwUug+AmAVOLdUIT4fAsW9pHQ/SOmLvEa3EJxF+Z5a+k8tCK8DAyaiFlYPYTqeQpkiHtXO+1q+klChjtH9HQMo5eoTMVfZAGFYpZSFh/3QSNXU08Bxd9nNSSLnAKc++e26hOrKdDQnMSiAW2bOwBwtSsfwG15f0M/m91KKEd6RiVZWzjBBwjQWwT0G67BiAlT/atP+CzJtjku+SGx3Vc=
